/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-05-14 15:20:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import did.*;

public final class Corsi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\tCorsi.jsp: \r\n");
      out.write("\tLa JSP visualizza la lista di tutti i corsi di studio attivi e gestiti da un\r\n");
      out.write("\tdiparitmento passato come parametro idDip.\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<!-- Eseguo gli import necessari -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
 
    // Genero un oggetto della classe DBMS per gestire l'interzione con la base di dati
   // did2013
    DBMS dbms = new DBMS();
    int ccs;
    //Ottengo l'eventuale parametro
    String idDip;
    if (request.getParameter("idDip") != null) // Ottengo se presente il parametro 'idDip'
	    idDip = (String)request.getParameter("idDip");
    else
	    idDip = "";

    //A seconda della presenza o meno del parametro la JSP varia il proprio comportamento
    if (idDip.equals("")) {  //parametro vuoto o assente: messaggio d'errore


      out.write(" \r\n");
      out.write("\t    <h2>Inserire il codice per gestire la mancanza del parametro idDip</h2>\r\n");
      out.write("       \r\n");
      out.write("\r\n");

    } else { 

      out.write('\r');
      out.write('\n');
	    // E' presente il parametro idDip.
	    // Si devono mostrare i dati dei corsi attivi nel dipartimento con id=idDip.
	    // -------------------------------------------------------------------------
	    // TODO
	    // INSERIRE IL CODICE PER L'ESTRAZIONE DEI DATI ATTRAVERSO I METODI 
	    // DELL'OGGETTO dbms E LA GENERAZIONE DEL CODICE HTML IN CUI SI PRESENTA
	    // L'ELENCO DEI CORSI DI STUDIO ATTIVI PRESSO IL DIPARTIMENTO
	    // ------------------------------------------------------------------------- 
      out.write("\r\n");
      out.write("\r\n");
 
            Vector css = dbms.getCorsoStudi(Integer.parseInt(idDip));
            CorsoStudiBean csb =(CorsoStudiBean) css.get(0);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Corsi di Studio Esistenti</title>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<h1>Corsi di Studio Esistenti:</h1>\r\n");
      out.write("<table borderspace=10>\r\n");
      out.write("<tr><th>Codice</th><th>Nome</th><th>Dipartimento</th></tr>\r\n");
      out.write("<tr><td> \r\n");
      out.write("    ");
      out.print( csb.getNomeCorsoStudi() );
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    </td><td> \r\n");
      out.write("\r\n");
      out.write("    ");
      out.print( csb.getDipartimento() );
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    </td></tr>\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<a href=\"Corsi.jsp\"><font color=\"00AA00\">Back</font></a>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
